CS50/CS50/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('UI.urls')),
    path('admin/', admin.site.urls),
]

airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ 
    path('users', include('users.urls')),
    path('flights', include('flights.urls')),
    path('admin/', admin.site.urls),
]

djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('newyear', include('newyear.urls')),
    path('cs50/', include('CS50.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

photoProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    # viewsモジュールのsignUpViewをインスタンス化する
    path('signup/', views.SignUpView.as_view(), name='signup'),
    # viewsモジュールのsignUpSuccessViewをインスタンス化する
    path('signup_success', views.SignUpSuccessView.as_view(), name='signup_success'),
    # ログイン django.contrib.auth.views.LoginViewをインスタンス化する
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # ログアウト django.contrib.auth.views.logoutViewをインスタンス化する
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

photoProject/photo/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前をつける
app_name = 'photo'

# URLパターンを登録するための変数
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreatePhotoView.as_view(), name='post'),
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    path('photos/<int:category>', views.CategoryView.as_view(), name='photos_cat'),
    path('user-list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('photo-detail/<int:pk>', views.DetailView.as_view(), name='photo_detail'),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('photo/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

photoProject/photo/models.py
from django.db import models
from accounts.models import CustomUser


class Category(models.Model):
    # カテゴリ名のフィールド
    title = models.CharField(
        verbose_name='カテゴリ',  # フィールドのタイトル
        max_length=20)

    def __str__(self):
        '''オブジェクトを文字列に変換して返す

        Returns(str):カテゴリ名
        '''
        return self.title


class PhotoPost(models.Model):
    '''モデルクラス
    '''
    # CustomUserモデル（のuser_id）とPhotoPostモデルを 1対多の関係で結びつける
    # CustomUserが親でPhotoPostが子
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='ユーザー',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除
        on_delete=models.CASCADE
    )

    # Categoryモデル（のtitle）とPhotoPostモデルを 1対多の関係で結びつける
    # Categoryが親でPhotoPostが子
    category = models.ForeignKey(
        Category,
        # フィールドのタイトル
        verbose_name='カテゴリ',
        # カテゴリに関連付けられた投稿データが存在する場合はそのカテゴリを削除できないように
        on_delete=models.PROTECT
    )

    # タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル',  # フィールドのタイトル
        max_length=20
    )

    # コメント用のフィールド
    comment = models.TextField(
        verbose_name='コメント',  # フィールドのタイトル
    )

    # イメージのフィールド1
    image1 = models.ImageField(
        verbose_name='イメージ1',  # フィールドのタイトル
        upload_to='photos'  # MEDIA_ROOT以下のphotosにファイルを保存
    )

    # イメージのフィールド2
    image2 = models.ImageField(
        verbose_name='イメージ2',  # フィールドのタイトル
        upload_to='photos',  # MEDIA_ROOT以下のphotosにファイルを保存
        blank=True,  # フィールド値の設定は必須ではない
        null=True  # DB値にnullを許容
    )

    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',  # フィールドのタイトル
        auto_now_add=True  # 日時を自動追加
    )

    def __str__(self):
        '''オブジェクトを文字列に変換して返す

        Returns(str): 投稿記事のタイトル
        '''
        return self.title

photoProject/photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
  '''ModelFormのサブクラス
  '''
  class Meta:
    '''ModelFormのインナークラス
    
    Attributes:
      model: モデルのクラス
      fields: フォームで使用するモデルのフィールドを指定
    '''
    model = PhotoPost
    fields = ['category', 'title', 'comment', 'image1', 'image2']

photoProject/photo/views.py
from django.shortcuts import render
# TemplateView, CreateViewをインポート
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView
# reverse_lazyをインポート
from django.urls import reverse_lazy
# PhotoPostFormをインポート
from .forms import PhotoPostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからモデルPhotoPostをインポート
from .models import PhotoPost


class IndexView(ListView):
    '''トップページのビュー
    '''
    template_name = 'index.html'
    # モデルPhotoPostのオブジェクトにorder_by()を適応して投稿日時の降順で並び替え
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコード件数
    paginate_by = 6

# デコレータによりCreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクト


@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    '''写真投稿ページのビュー

    PhotoPostFormで定義されているモデルとフィールドと連携して投稿データをDBに登録する

    Attributes:
        form_class: モデルとフィールドが登録されたフォームクラス
        template_name: レンダリングするテンプレート
        success_url: DBへの登録完了後、リダイレクト先
    '''
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = 'post_photo.html'
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド

        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う

        parameters:
            form(django.forms.Form):
                form_classに格納されているPhotoPostFromオブジェクト
        Return:
            HttpResponseRedirectオブジェクト:
                スーパークラスのform_valid()の戻り値を返すことで、success_urlで設定されているURLにリダイレクト
        '''
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをDBに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)


class PostSuccessView(TemplateView):
    '''投稿完了のページのビュー

    Attributes:
        template_name: レンダリングするテンプレート
    '''
    template_name = 'post_success.html'


class CategoryView(ListView):
    '''カテゴリページのビュー

    Attributes:
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコード件数
    '''
    template_name = 'index.html'
    paginate_by = 6

    def get_queryset(self):
        '''クエリの実行

        self.kwargsの取得が必要なので、クラス変数querysetではなく、get_queryset()のオーバーライド

        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、categoryキーの値（Categorysテーブルのid）を取得
        category_id = self.kwargs['category']
        # filterで絞り込み
        categories = PhotoPost.objects.filter(
            category=category_id).order_by('-posted_at')
        # クエリの結果を返す
        return categories


class UserView(ListView):
    '''ユーザー投稿一覧ページのビュー

    Attributes:
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコード件数
    '''
    template_name = 'index.html'
    paginate_by = 6

    def get_queryset(self):
        '''クエリを実行する

        self.kwargsの取得が必要なため、get_queryset()のオーバーライド

        Returns:
            クエリによって取得されたレコード
        '''
        # self.kwargsからuserキーの値（「ユーザー」テーブルのid）を取得
        user_id = self.kwargs['user']
        # filterで絞り込み
        user_list = PhotoPost.objects.filter(
            user=user_id).order_by('-posted_at')
        # クエリの結果を返す
        return user_list


class DetailView(DetailView):
    '''詳細ページのビュー

    投稿記事の詳細を表示
    Attributes:
        template_name: レンダリングするテンプレート
        model: モデルクラス
    '''
    template_name = 'detail.html'
    model = PhotoPost


class MypageView(ListView):
    '''マイページのビュー

    Attributes:
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコード数
    '''
    template_name = 'mypage.html'
    paginate_by = 6

    def get_queryset(self):
        '''クエリを実行する

        self.kwargsの取得が必要なため、get_queryset()のオーバーライド

        Returns:
            クエリによって取得されたレコード
        '''
        # 現在ログインしているユーザー名はHttpRequest.userに格納されている
        # filter(userフィールド=userオブジェクト)で絞り込み
        queryset = PhotoPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        return queryset


class PhotoDeleteView(DeleteView):
    '''レコードの削除

    Attributes:
        model: モデル
        template_name: レンダリングするテンプレート
        paginate_by: 1ページに表示するレコード数
        success_url: 削除完了後のリダイレクト先
    '''
    # 操作対象はPhotoPostモデル
    model = PhotoPost
    # レンダリングするテンプレート
    template_name = 'photo_delete.html'
    # 削除完了後のリダイレクト先
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        '''django.views.generic.edit.DeletionMixin.delete()のオーバーライド

            Parameters:
                self: PhotoDeleteViewオブジェクト
                request: WSGIRequest(HttpRequest)オブジェクト
                args: 引数として渡される辞書
                kwargs: キワード付き辞書
            
            Returns:
                HttpResponseRedirect(success_url)を返してsuccess_urlにリダイレクト
        '''
        return super().delete(request, *args, **kwargs)

photoProject/photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.79.0">
  <title>{% block title %}{% endblock %}</title>



  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


</head>

<body>

  <header>
    <div class="collapse bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">お気に入りを見つけよう！</h4>
            <p class="text-muted">誰でも参加できる写真投稿サイトです。カテゴリに属する写真のみの投稿になります。</p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Contact</h4>
            <ul class="list-unstyled">
              {% if user.is_authenticated %}
                <!-- ログイン中 -->
                <li><a href="{% url 'photo:mypage' %}" class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
                <li><a href="#" class="text-white">パスワードのリセット(未実装)</a></li>
                <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
              {% else %}
                <!-- 非ログイン -->
                <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
            stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
            viewBox="0 0 24 24">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
            <circle cx="12" cy="13" r="4" />
          </svg>
          <strong>Photo Gallery</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
          aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>

  <main>
    {% block contents %}{% endblock %}
  </main>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Photo Gallery is &copy; Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
          href="../getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>


</body>

</html>

photoProject/photo/templates/detail.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

{% block contents %}
<br>
<div class="container">
  <div class="row">
    <div class="col offset-3">
      <h2>{{ object.title }}</h2>
      <p>{{ object.comment }}</p>
      <br>
      <p>{{ object.posted_at }}に投稿</p>
      <p><img src="{{ object.image1.url }}" alt=""></p>
      {% if object.image2 %}
        <p><img src="{{ object.image2.url }}" alt=""></p>
      {% endif %}

      <!-- 投稿がログイン中のユーザーのものであれば削除ボタンを表示 -->
      {% if request.user == object.user %}
        <!-- photo/<Photo postsテーブルのid値>/delete -->
        <a href="{% url 'photo:photo_delete' object.pk %}" class="btn btn-danger my-2">削除する</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

photoProject/photo/templates/index.html
{% extends 'base.html' %}

{% block title %}Photo Gallery{% endblock %}

{% block contents %}

{% include 'photos_title.html' %}
{% include 'photos_list.html' %}
<!-- ページネーションの組み込み -->
{% include 'pagination.html' %}

{% endblock %}

photoProject/photo/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}

{% block contents %}
<!-- ユーザーの投稿件数を表示 -->
{% if user.is_authenticated %}
  <br>
  <div style="text-align: center;">
    <h4>{{ user.username }}のマイページ</h4>
    {% if object_list.count == 0 %}
      <p>{{ user.username }}の投稿はありません</p>
    {% else %}
      <p>投稿<strong>{{ object_list.count }}</strong>件</p>
    {% endif %}
    <a href="{% url 'photo:post' %}">投稿する</a>
  </div>
  <hr>
{% endif %}

<!-- 投稿一覧テンプレートの組み込み -->
{% include 'photos_list.html' %}

{% include 'pagination.html' %}

{% endblock %}

photoProject/photo/templates/pagination.html
<!-- is_paginated 表示結果がページ分割されているかどうかを示す真偽値
     オブジェクトの個数が paginate_by と等しいか
     それ以下の場合、False になる
-->
{% if is_paginated %}
<ul class="pagination" style="justify-content: center;">

  <!-- Page.has_previous 前のページがある場合、True を返す -->
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
      <!-- ↓ bootstrap で 矢印マークを表示するためのエスケープ -->
      <span aria-hidden="true">&laquo;</span>
    </a>
  </li>
  {% endif %}

  <!-- ページ数の表示
       paginator.page_range: [1, 2, 3, 4] のように、1 から始まるページ番号
  -->
  {% for num in paginator.page_range %}
  {% if page_obj.number == num %}
  <li class="page-item active">
    <span class="page-link">{{num}}</span>
  </li>
  {% else %}
  <li class="page-item">
    <a href="?page={{num}}" class="page-link">{{num}}</a>
  </li>
  {% endif %}
  {% endfor %}

  <!-- 次ページヘのリンク
       Page.next_page_number: 次のページがある場合に True を返す
  -->
  {% if page_obj.has_next %}
  <li class="page-item">
    <a href="?page={{page_obj.next_page_number}}" class="page-link" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
    </a>
  </li>
  {% endif %}
</ul>
{% endif %}

photoProject/photo/templates/photo_delete.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="col offset-3">
      <br>
      <p>削除しますか？</p>
      <form method="post">
        {% csrf_token %}
        <input type="submit" value="削除する" class="btn my-2 btn-danger">
      </form>
      <a href="{% url 'photo:photo_detail' object.pk %}" class="btn btn-primary my-2">キャンセル</a>
    </div>
  </div>
</div>
{% endblock %}

photoProject/photo/templates/photos_list.html
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <!-- レコードが格納されたobject_listからレコードを一行ずつrecordに取り出す -->
      {% for record in object_list %}
      <div class="col">
        <div class="card shadow-sm">
          <image src="{{ record.image1.url }}" class="bd-placeholder-img card-img-top img-thumbnail" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c" />
          </image>

          <div class="card-body">
            <p class="card-text">
              {{ record.title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <!-- 投稿詳細へ -->
                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">View</button>
                <!-- カテゴリ表示ボタン -->
                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">{{ record.category.title }}</button>
              </div>
              <!-- 投稿したユーザー名を出力し、一覧ページへのリンクを設定 -->
              <a href="{% url 'photo:user_list' user=record.user.id %}">
                <small class="text-muted">
                  {{ record.user.username }}
                </small>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</div>

photoProject/photo/templates/photos_title.html
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Photo Gallery</h1>
      <p class="lead text-muted">コメントで、写真に描かれた世界に思いを馳せましょう。素敵な写真とコメントをお待ちしております。
      </p>
      <p>
        {% if user.is_authenticated %}
          <a href="{% url 'photo:post' %}" class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
        {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
        {% endif %}
      </p>
    </div>
  </div>
</section>

photoProject/photo/templates/post_photo.html
{% extends 'base.html' %}

{% block title %}Post{% endblock %}

{% block contents %}
<!-- Bootstrapのグリッドシステム -->
<br>
<div class="container">
  <div class="row">
    <div class="col offset-2">
      <!-- ファイルアップロード -->
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          <tr>
            <th>カテゴリ</th>
            <td>{{ form.category }}</td>
          </tr>
          <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
          </tr>
          <tr>
            <th>コメント</th>
            <td>{{ form.comment }}</td>
          </tr>
          <tr>
            <th>画像1</th>
            <td>{{ form.image1 }}</td>
          </tr>
          <tr>
            <th>画像2</th>
            <td>{{ form.image2 }}</td>
          </tr>
        </table>
        <hr>
        <button type="submit">投稿する</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

photoProject/photo/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

{% block contents %}
<br><br>
<div class="container">
  <div class="row">
    <div class="col offset-2">
      <h4>投稿が完了しました!</h4>
    </div>
  </div>
</div>
{% endblock %}