CS50/CS50/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('UI.urls')),
    path('admin/', admin.site.urls),
]

airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ 
    path('users', include('users.urls')),
    path('flights', include('flights.urls')),
    path('admin/', admin.site.urls),
]

djangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('newyear', include('newyear.urls')),
    path('cs50/', include('CS50.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

firstProject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

# viewsモジュールのIndexViewクラスをインスタンス化する
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blog-detail/<int:pk>/', views.BlogDetail.as_view(), name="blog_detail"),
    path('nogizaka-list/', views.NogizakaView.as_view(), name="nogizaka_list"),
    path('hinatazaka-list/', views.HinatazakaView.as_view(), name="hinatazaka_list"),
    path('sakurazaka-list/', views.SakurazakaView.as_view(), name="sakurazaka_list"),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

firstProject/blog/models.py
from django.db import models


class BlogPost(models.Model):
    '''モデルクラス'''
    CATEGORY = (("nogizaka", "乃木坂46"),
                ("hinatazaka", "日向坂46"), ("sakurazaka", "櫻坂46"))

    # タイトル用フィールド
    title = models.CharField(
        verbose_name="タイトル",
        max_length=200,
    )

    # 本文用タイトル
    content = models.TextField(
        verbose_name="本文",
    )

    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name="投稿日時",
        auto_now_add=True,
    )

    # カテゴリのフィールド
    category = models.CharField(
        verbose_name="カテゴリ",
        max_length=50,
        choices=CATEGORY,
    )

    def __str__(self):
        return self.title

firstProject/blog/views.py
from django.shortcuts import render

# django.views.genericからListViewをインポートする
from django.views.generic import ListView, DetailView

from .models import BlogPost


class IndexView(ListView):
    '''トップページビュー

    投稿記事を一覧表示するのでListViewを継承する

    Attributes:
        template_name: レンダリングするテンプレート
        context_object_name: object_listキーの別名を設定
        queryset: DBのクエリ
    '''

    template_name = "index.html"
    # object_listキーの別名を設定
    context_object_name = "orderby_records"
    # BlogPostレコードを、投稿日時の降順で表示
    queryset = BlogPost.objects.order_by("-posted_at")

    paginate_by = 4


class BlogDetail(DetailView):
    '''詳細ページのビュー

    投稿記事の詳細を表示するのでDetailViewを継承する

    Attributes:
        template_name: レンダリングするテンプレート
        Model: モデルのクラス
    '''
    template_name = "post.html"
    model = BlogPost


class NogizakaView(ListView):
    template_name = "nogizaka.html"
    model = BlogPost
    context_object_name = "nogizaka_records"
    queryset = BlogPost.objects.filter(
        category="nogizaka").order_by("-posted_at")
    paginate_by = 2


class HinatazakaView(ListView):
    template_name = "hinatazaka.html"
    model = BlogPost
    context_object_name = "hinatazaka_records"
    queryset = BlogPost.objects.filter(
        category="hinatazaka").order_by("-posted_at")
    paginate_by = 2


class SakurazakaView(ListView):
    template_name = "sakurazaka.html"
    model = BlogPost
    context_object_name = "sakurazaka_records"
    queryset = BlogPost.objects.filter(
        category="sakurazaka").order_by("-posted_at")
    paginate_by = 2

firstProject/blog/templates/base.html
<!-- staticタグのロード -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>{% block title %}{% endblock%}</title>
  <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
    type="text/css" />
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
    rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href={% static 'css/styles.css' %} rel="stylesheet" />
</head>

<body>
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href={% url 'blog:index' %}>Django's Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto py-4 py-lg-0">
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href={% url 'blog:index' %}>Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:nogizaka_list' %}">Nogizaka</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:hinatazaka_list' %}">Hinatazaka</a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:sakurazaka_list' %}">Sakurazaka</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Header-->
  {% block header %}{% endblock %}
  <!-- Main Content-->
  {% block content %}{% endblock %}
  <!-- Footer-->
  <footer class="border-top">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/YoKaU2">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.com/kngy0306">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <div class="small text-center text-muted fst-italic">
            Copyright &copy; Django's Blog 2021
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src={% static 'js/scripts.js' %}></script>
</body>

</html>

firstProject/blog/templates/hinatazaka.html
{% extends 'base.html' %}
<!-- staticタグのロード -->
{% load static %}

{% block title %}Django's Blog - Hinatazaka{% endblock %}

<!-- Page Header-->
{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Django's Blog</h1>
          <span class="subheading">日向坂46の一覧</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
<!-- Main Content-->
{% block content %}
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for record in hinatazaka_records %}
      <div class="post-preview">
        <a href="{% url 'blog:blog_detail' record.pk %}">
          <h2 class="post-title">
            {{ record.title }}
          </h2>
          <h3 class="post-subtitle">
            <span style="font-size: 16pt;">
              <!-- 出力文字数を50字に制限 -->
              {{record.content|truncatechars:50}}
            </span>
          </h3>
        </a>
        <p class="post-meta">
          <a href="#">Django's Blog</a>
          {{record.posted_at}}に投稿/カテゴリ:
          {{record.category}}
        </p>
      </div>
      <hr>
      {% endfor %}

      <!-- ページネーション -->
      {% include "pagination.html" %}
    </div>
  </div>
</div>
{% endblock %}
<!-- Footer-->

firstProject/blog/templates/index.html
<!-- staticタグのロード -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Django's Blog</title>
    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %}
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href={% static 'css/styles.css' %} rel="stylesheet" />
  </head>

  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href={% url 'blog:index' %}>Django's Blog</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href={% url 'blog:index' %}
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html"
                >Sample Post</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html"
                >Contact</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Header-->
    <header
      class="masthead"
      style="background-image: url({% static 'assets/img/home-bg.jpg' %})"
    >
      <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="site-heading">
              <h1>Clean Blog</h1>
              <span class="subheading">A Blog Theme by Start Bootstrap</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <!-- Post preview-->
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                Man must explore, and this is exploration at its greatest
              </h2>
              <h3 class="post-subtitle">
                Problems look mighty small from 150 miles up
              </h3>
            </a>
            <p class="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on September 24, 2021
            </p>
          </div>
          <!-- Divider-->
          <hr class="my-4" />
          <!-- Post preview-->
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">
                I believe every human has a finite number of heartbeats. I don't
                intend to waste any of mine.
              </h2>
            </a>
            <p class="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on September 18, 2021
            </p>
          </div>
          <!-- Divider-->
          <hr class="my-4" />
          <!-- Post preview-->
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">Science has not yet mastered prophecy</h2>
              <h3 class="post-subtitle">
                We predict too much for the next year and yet far too little for
                the next ten.
              </h3>
            </a>
            <p class="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on August 24, 2021
            </p>
          </div>
          <!-- Divider-->
          <hr class="my-4" />
          <!-- Post preview-->
          <div class="post-preview">
            <a href="post.html">
              <h2 class="post-title">Failure is not an option</h2>
              <h3 class="post-subtitle">
                Many say exploration is part of our destiny, but it’s actually
                our duty to future generations.
              </h3>
            </a>
            <p class="post-meta">
              Posted by
              <a href="#!">Start Bootstrap</a>
              on July 8, 2021
            </p>
          </div>
          <!-- Divider-->
          <hr class="my-4" />
          <!-- Pager-->
          <div class="d-flex justify-content-end mb-4">
            <a class="btn btn-primary text-uppercase" href="#!"
              >Older Posts →</a
            >
          </div>
        </div>
      </div>
    </div>
    <!-- Footer-->
    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://twitter.com/YoKaU2">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/kngy0306">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">
              Copyright &copy; Django's Blog 2021
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src={% static 'js/scripts.js' %}></script>
  </body>
</html>

firstProject/blog/templates/nogizaka.html
{% extends 'base.html' %}
<!-- staticタグのロード -->
{% load static %}

{% block title %}Django's Blog - Nogizaka{% endblock %}

<!-- Page Header-->
{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Django's Blog</h1>
          <span class="subheading">乃木坂46の一覧</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
<!-- Main Content-->
{% block content %}
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for record in nogizaka_records %}
      <div class="post-preview">
        <a href="{% url 'blog:blog_detail' record.pk %}">
          <h2 class="post-title">
            {{ record.title }}
          </h2>
          <h3 class="post-subtitle">
            <span style="font-size: 16pt;">
              <!-- 出力文字数を50字に制限 -->
              {{record.content|truncatechars:50}}
            </span>
          </h3>
        </a>
        <p class="post-meta">
          <a href="#">Django's Blog</a>
          {{record.posted_at}}に投稿/カテゴリ:
          {{record.category}}
        </p>
      </div>
      <hr>
      {% endfor %}

      <!-- ページネーション -->
      {% include "pagination.html" %}
    </div>
  </div>
</div>
{% endblock %}
<!-- Footer-->

firstProject/blog/templates/post.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Django's Blog{% endblock %}
<!-- Page Header-->
{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{object.title}}</h1>
                    <h2 class="subheading">{{object.content|truncatechars:30}}</h2>
                    <span class="meta">
                        <a href="{% url 'blog:index' %}">Django's Blog</a>
                        {{object.posted_at}}に投稿/カテゴリ:
                        {{object.category}}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
<!-- Post Content-->
{% block content %}
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>{{object.content}}</p>
            </div>
        </div>
    </div>
</article>
{% endblock %}

firstProject/blog/templates/sakurazaka.html
{% extends 'base.html' %}
<!-- staticタグのロード -->
{% load static %}

{% block title %}Django's Blog - Sakurazaka{% endblock %}

<!-- Page Header-->
{% block header %}
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Django's Blog</h1>
          <span class="subheading">櫻坂46の一覧</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
<!-- Main Content-->
{% block content %}
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for record in sakurazaka_records %}
      <div class="post-preview">
        <a href="{% url 'blog:blog_detail' record.pk %}">
          <h2 class="post-title">
            {{ record.title }}
          </h2>
          <h3 class="post-subtitle">
            <span style="font-size: 16pt;">
              <!-- 出力文字数を50字に制限 -->
              {{record.content|truncatechars:50}}
            </span>
          </h3>
        </a>
        <p class="post-meta">
          <a href="#">Django's Blog</a>
          {{record.posted_at}}に投稿/カテゴリ:
          {{record.category}}
        </p>
      </div>
      <hr>
      {% endfor %}

      <!-- ページネーション -->
      {% include "pagination.html" %}
    </div>
  </div>
</div>
{% endblock %}
<!-- Footer-->